### ISSUE TITLE
[Tracking]: 1.73.x Feature/Enhancement Candidates

### ISSUE THREAD

**Issue by bagusnl** [CollapseLauncher/Collapse#359]
# Features candidates
- [x] Add `Extract anyway` button when a downloaded package is corrupted.
   > This is a mean to not force user to redownload the whole game update/installation package when their currently downloaded one is corrupted. User needs to be told that this operation is risky and might lead to game not behaving normally. User is also expected to run a Full Game Repair when this feature is used.
  > Done by @neon-nyan as of https://github.com/CollapseLauncher/Collapse/commit/59d107eb1284e665775a2aee919728c662686c55

- [x] Adjust CommunityTools' Official Tools list for CN region
  > This requires another list as the links are different for Mainland China (inc. Bilibili) game region.
  > Assigned to @shatyuka 
  > Completed per https://github.com/CollapseLauncher/Collapse/pull/369
  
- [x] Implement new command line and add to steam feature
  > Assigned to @gablm 
  > Related to #358 
  > Finished as of https://github.com/CollapseLauncher/Collapse/commit/3f8c4a3a25e8d3b7ef02350fdd1d65e5a64978df

- [x] Add toggle for Custom Launch Arguments
  > Related to #361 
  > Assigned to @bagusnl 
  > Completed with https://github.com/CollapseLauncher/Collapse/commit/b1922e8e23f1dbc9c648c6892527a91d4b4634e0

- [x] Add toggle to always use external browser
  > Hook into `WebView2FramePage.WebView2FramePage()`
  > Assigned to @bagusnl 
  > Completed with https://github.com/CollapseLauncher/Collapse/commit/e29cf5e00abd06d1a7fd483397d84a7a4d70d716

- [x] Reimplement game migration (move game files)
  > Related to #370
  > Assigned to @neon-nyan 
  > Completed with https://github.com/CollapseLauncher/Collapse/commit/d5ad7514d528b93278ef7d75285cef0cd639f136

# Enhancement candidates
- [x] Make game selection localizable
  > Done by @neon-nyan as of https://github.com/CollapseLauncher/Collapse/commit/82051c9837ffee4164c5e36cf6a54dd62bcf7801

- [ ] Set `AppUserModelID` globally to prevent double taskbar issue
  > Related to #142 

- [x] Disable Discord RPC on `Idle` state
  > Toggleable
  > ~~Assigned to @bagusnl~~
  > Searching for a fix where RPC content is not reinitialized when it came back.
  
### Additional context

This issue will be edited accordingly during the development. Will be closed when 1.73.x is promoted to Stable.
